source 'https://svrgitpub.sdos.es/iOS/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'SDOSPluggableApplicationDelegateExample' do
  pod 'SDOSPluggableApplicationDelegate', :path => '../../'

  target 'SDOSPluggableApplicationDelegateExample_Tests' do
    inherit! :search_paths

    
  end
end
